### ISSUE TITLE
Add SDK.Player.IsWormholeJumping()

### ISSUE THREAD

**Issue by victorpopkov** [dstmodders/mod-sdk#8]
### Verify

- [X] I understand that if I ignore these instructions, my **issue may be closed without review**.
- [X] I have made sure that there are **no similar opened issues**.
- [X] I have made sure that the **SDK version matches the latest release**.

### Is your feature request related to a problem? Please describe.

Suggested by @sauktux. Related to https://github.com/dstmodders/mod-keep-following/pull/16.

### Describe the solution you'd like

```lua
local function IsWormholeJumping(player)
    if
        player
        and player.entity:IsValid()
        and player.entity:IsVisible()
        and (player.sg or player.AnimState)
    then
        if player.sg and player.sg.HasStateTag and player.sg:HasStateTag("jumpin") then
            return true
        end

        if player.AnimState and not player.AnimState.IsCurrentAnimation then
            return nil
        end

        return player.AnimState:IsCurrentAnimation("dissipate")
            or player.AnimState:IsCurrentAnimation("heavy_jump")
            or player.AnimState:IsCurrentAnimation("jump")
    end
    return nil
end
```

### Describe alternatives you've considered

If applicable, add a clear and concise description of any alternative solutions or features you've considered.

### Additional context

If applicable, add any other context or screenshots about the feature request here.

**Comment by sauktux** [comment]
I believe the following code snippet:
```
if player.sg and player.sg.HasStateTag and player.sg:HasStateTag("jumpin") then
    return true
end
```
should be changed to:
```
if player.sg and player.sg.currentstate and player.sg.currentstate.name == "jumpin" then
    return true
end
```
as the "jumpin" state does not actually have any unique tags, not even the "jumpin" tag, thus the HasStateTag function won't ever return true through the stategraph method. This is also the current code that is in the commit https://github.com/dstmodders/mod-keep-following/pull/16/commits/7dc61ea39310239b12e91110462f87d7895aaa3f in https://github.com/dstmodders/mod-keep-following/pull/16
